import { StyleSheet } from "react-native";

export const VIDEO_HEIGHT = 180;

export const styleUserHome = StyleSheet.create({
  txtboasv: {
    fontSize: 20,
    marginTop: 40,
    marginBottom: 80,
    fontWeight: "200",
    backgroundColor: "white",
    justifyContent: "center",
    alignItems: "center",
    textAlign: "center",
  },
  inicio: {
    justifyContent: "center",
    alignItems: "center",
  },
  img: {
    width: 250,
    height: 100,
    justifyContent: "center",
    alignItems: "center",
  },
  lougout: {
    height: 60,
  },
  sairtxt: {
    height: 60,
    textAlign: "center",
    justifyContent: "center",
    fontSize: 17,
    marginTop: 15,
    marginLeft: 5,
    flexDirection: "row",
    fontWeight: "300",
  },
  btn: {
    width: 173,
    height: 230,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "white",
    backgroundColor: "white",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 13,
    margin: 5,
    shadowColor: "black",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.7,
    shadowRadius: 2,
    elevation: 5,
  },
  txtbtn: {
    color: "#00000098",
    fontSize: 15,
    textAlign: "center",
    fontWeight: "300",
    marginTop: 15,
    borderTopColor: "#00000098",
    borderTopWidth: 1,
    fontWeight: "bold",
  },
  txttutorial: {
    textAlign: "center",
    fontSize: 22,
    marginBottom: 10,
    fontWeight: "200",
    margin: -69,
  },
  tIncriarsala: {
    width: 250,
    height: 50,
    borderRadius: 100,
    borderWidth: 1,
    borderColor: "#EFC8EF",
    backgroundColor: "#EFC8EF",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 72,
    textDecorationColor: "white",
    textAlign: "center",
    shadowColor: "black",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.7,
    shadowRadius: 2,
    elevation: 5,
  },
  imgModal: {
    width: 398,
    height: 555,
    marginRight: 0,
  },
  btn1: {
    width: 250,
    height: 50,
    borderWidth: 1,
    borderColor: "white",
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    marginTop: -5,
    margin: 5,
    borderRadius: 100,
    shadowColor: "black",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.7,
    shadowRadius: 2,
    elevation: 5,
  },
  btnCancel: {
    height: 40,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 25,
  },
  btnTextCan: {
    color: "#d3d3d3",
  },
  btnTextCiar: {
    color: "white",
    fontWeight: "bold",
  },

  imgHomeU: {
    width: 380,
    height: 290,
    marginRight: 0,
    marginTop: 0,
  },
  bemvind: {
    backgroundColor: "white",
    width: 100,
    height: 50,
  },
  imgBtn1: {
    width: 173,
    height: 230,
    borderRadius: 10,
    marginTop: 10,
    borderRadius: 10,
    margin: 7,
  },
  icon1: {
    width: 173,
    height: 230,
    marginTop: -30,
    margin: 0,
    marginLeft: -17,
  },
  txtbtn2: {
    color: "#00000098",
    fontSize: 15,
    textAlign: "center",
    fontWeight: "300",
    marginTop: 10,
    borderTopColor: "#00000098",
    borderTopWidth: 1,
    fontWeight: "bold",
  },
  txtbtn3: {
    color: "#00000098",
    fontSize: 15,
    textAlign: "center",
    fontWeight: "300",
    marginTop: -160,
    borderTopColor: "#00000098",
    borderTopWidth: 1,
  },
  imgRec: {
    height: 40,
    width: 300,
    marginTop: 20,
    margin: 20,
    marginLeft: 45,
  },
  imgAnun: {
    height: 30,
    width: 280,
    marginTop: 20,
    margin: 20,
    marginLeft: 45,
  },
});
