import { StyleSheet } from "react-native";

export const stylesHome = StyleSheet.create({
  img: {
    width: 340,
    height: 45,
    marginTop: 250,
  },
  btn: {
    width: 250,
    height: 50,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#DBA3DB",
    backgroundColor: "#DBA3DB",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 20,
  },
  txtbtn: {
    color: "white",
    fontSize: 15,
    textAlign: "center",
    fontWeight: "300",
  },
  meio: {
    marginTop: 250,
    alignItems: "center",
    justifyContent: "center",
  },
  gif: {
    width: 300,
    height: 300,
  },
  gif2: {
    width: 300,
    height: 300,
    marginTop: 100,
  },
  frase: {
    width: 280,
    height: 40,
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 10,
  },
  frase2: {
    width: 280,
    height: 45,
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 10,
  },
  box: {
    width: "90%",
    height: "100%",
    //backgroundColor: "#ffcbff",
    borderRadius: 5,
    margin: 15,
  },
  listas: {
    marginTop: 50,
    width: "85%",
  },
  touchable: {
    width: 200,
    height: 200,
    backgroundColor: "#dba3db",
    borderRadius: 20,
    margin: 10,
    padding: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  modal: {
    width: "90%",
    height: "50%",
    backgroundColor: "#f6e1f6",
    justifyContent: "center",
    alignItems: "center",
    textAlign: "center",
    borderRadius: 20,
    borderColor: "#edc9ed",
    borderWidth: 1,
  },
  imgmodal: {
    height: 130,
    width: 290,
  },
  itemContent: {
    width: 300,
    height: 300,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#e0e0e0",
    padding: 16,
    borderRadius: 16,
  },
  txtmodal: {
    width: 250,
    height: 200,
    textAlign: "center",
    marginTop: 25,
    fontWeight: "300",
  },
  txtmodalbtn: {
    fontWeight: "200",
    justifyContent: "flex-end",
    marginTop: 20,
    fontSize: 18,
  },

  footerlogo: {
    width: 120,
    height: 50,
    alignItems: "center",
    justifyContent: "center",
  },
  footer: {
    alignItems: "center",
    justifyContent: "center",
  },
  gifmodal: {
    width: 20,
    height: 20,
  },
});
