import { StyleSheet } from "react-native";

export const VIDEO_HEIGHT = 180;

export const styleUserHome = StyleSheet.create({
  txtboasv: {
    fontSize: 20,
    marginTop: 40,
    marginBottom: 80,
    fontWeight: "200",
    backgroundColor: "white",
    justifyContent: "center",
    alignItems: "center",
    textAlign: "center",
  },
  inicio: {
    justifyContent: "center",
    alignItems: "center",
  },
  img: {
    width: 250,
    height: 100,
    justifyContent: "center",
    alignItems: "center",
  },
  lougout: {
    height: 60,
  },
  sairtxt: {
    height: 60,
    textAlign: "center",
    justifyContent: "center",
    fontSize: 17,
    marginTop: 15,
    marginLeft: 5,
    flexDirection: "row",
    fontWeight: "300",
  },
  btn: {
    width: 173,
    height: 230,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "white",
    backgroundColor: "white",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 13,
    margin: 5,
  },
  txtbtn: {
    color: "white",
    fontSize: 15,
    textAlign: "center",
    fontWeight: "300",
    marginTop: 198,
    borderTopColor: "white",
    borderTopWidth: 1,
  },
  txttutorial: {
    textAlign: "center",
    fontSize: 22,
    marginBottom: 10,
    fontWeight: "200",
    margin: -69,
  },
  tIncriarsala: {
    width: 250,
    height: 50,
    borderRadius: 100,
    borderWidth: 1,
    borderColor: "#D87AD8",
    backgroundColor: "#D87AD8",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 72,
    textDecorationColor: "white",
    textAlign: "center",
  },
  imgModal: {
    width: 378,
    height: 475,
    marginRight: 0,
    marginTop: -55,
  },
  btn1: {
    width: 250,
    height: 50,
    borderRadius: 100,
    borderWidth: 1,
    borderColor: "#F6DEF6100",
    backgroundColor: "#F6DEF6100",
    alignItems: "center",
    justifyContent: "center",
    marginTop: -5,
    margin: 5,
  },
  btnCancel: {
    height: 40,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 50,
  },
  btnTextCan: {
    color: "#d3d3d3",
  },
  btnTextCiar: {
    color: "white",
    fontWeight: "bold",
  },

  imgHomeU: {
    width: 380,
    height: 290,
    marginRight: 0,
    marginTop: 0,
  },
  bemvind: {
    backgroundColor: "white",
    width: 100,
    height: 50,
  },
  imgBtn1: {
    width: 173,
    height: 230,
    borderRadius: 10,
    marginTop: 10,
    borderRadius: 10,
    margin: 7,
  },
});
