import { StyleSheet } from "react-native";

export const styleTarefa = StyleSheet.create({
  inicio: {
    backgroundColor: "white",
    flex: 1,
  },
  img: {
    width: "100%",
    height: 170,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 0,
    marginBottom: 50,
  },
  btn: {
    width: 250,
    height: 50,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#DBA3DB",
    backgroundColor: "#DBA3DB",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 20,
  },
  add: {
    fontSize: 15,
    textAlign: "center",
    fontWeight: "500",
    color: "black",
    borderRadius: 5,
    height: 50,
    width: 375,
    backgroundColor: "white",
    marginLeft: 2,
    marginTop: 15,
    shadowColor: "black",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.7,
    shadowRadius: 2,
    elevation: 5,
  },
  btnimg: {
    marginTop: 15,
    shadowColor: "black",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.7,
    shadowRadius: 2,
    elevation: 5,
  },
  textoo: {
    fontSize: 18,
    fontWeight: "200",
    marginTop: 20,
    borderBottomWidth: 1,
    borderBottomColo: "black",
  },
  iconeprimeiro: {
    alignItems: "flex-start",
    marginLeft: 10,
    justifyContent: "center",
    marginTop: 20,
  },
  textarefa: {
    color: "black",
    marginLeft: 10,
    fontWeight: "400",
    textAlign: "left",
    width: 270,
  },
  iconetrash: {
    alignItems: "flex-end",
    marginTop: 20,
  },
  txtcodigo: {
    fontWeight: "300",
    textAlign: "center",
    marginLeft: 10,
  },
  ver: {
    marginLeft: 5,
  },
  centeredView: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 22,
  },
  modalView: {
    margin: 20,
    backgroundColor: "white",
    borderRadius: 20,
    padding: 35,
    alignItems: "center",
    shadowColor: "#000",
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    width: 340,
    height: 650,
  },
  modalText: {
    marginBottom: 15,
    textAlign: "center",
    fontWeight: "300",
    fontSize: 18,
  },
  modalUsers: {
    marginBottom: 15,
    textAlign: "center",
    fontWeight: "300",
  },
});
